server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # This line is the magic: it redirects 404s to index.html
        try_files $uri $uri/ /index.html;
    }

    # Optional: Cache static assets for better performance
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}
Gateway & Proxy ConfigurationTo prevent exposing application servers directly to the internet, we add an Nginx reverse proxy configuration.
events { worker_connections 1024; }
http {
    upstream backend_servers {
        server backend-service.lab-shopflow.svc.cluster.local:5000;
    }
    server {
        listen 80;
        location /api/ {
            rewrite /api/(.*) /$1 break;
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }
    }
}
