sonar.organization=henoknathan
# Make the project key unique to this specific application to prevent collisions
sonar.projectKey=henoknathan-shopflow-k8s-prod-app
sonar.projectName=Shopflow-K8s-Application
# Change this from '.' to the specific directory where your app code lives (e.g., src, frontend, or backend)
sonar.sources=src
sonar.language=java
