apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-tier-ingress
  namespace: lab-shopflow
  annotations:
    # --- Baseline AWS Settings ---
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: enterprise-alb
    
    # --- SSL/TLS & HTTPS Configuration ---
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:514497148354:certificate/YOUR-ACM-GUID-HERE"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    
    # --- CLEAN HTTPS REDIRECT ACTION ---
    # Automatically manages port 80 -> 443 upgrades natively without dirty path workarounds
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    
    # --- GLOBAL HEALTH CHECK DEFAULTS ---
    # Since all app paths flow into Nginx, Nginx answers 200 OK on '/' natively
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      # 1. Grafana Monitoring Interface (Kept separate for administrative control)
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: monitor-stack-grafana 
            port:
              number: 80

      # 2. Main Application Entrypoint
      # Handles rendering the E-commerce UI AND intercepts '/api' internally via Nginx proxy loops
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shopflow-frontend-svc # MATCHES: The Frontend Service from your main manifest
            port:
              number: 80
