apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: lab-shopflow
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
# 2. MySQL StatefulSet (The Correct Engine for Databases)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: lab-shopflow
spec:
  serviceName: "mysql-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # FIXES AWS EFS PERMISSION DENIED BUG:
      # Pre-configures storage folder ownership so MySQL can read/write to EFS
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 999:999 /var/lib/mysql"]
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql

      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-password
        - name: MYSQL_DATABASE
          value: "shopflow_db" 
        ports:
        - containerPort: 3306
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql

      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          # FIXED: Synchronized name to point directly to your primary storage pool
          claimName: shared-efs-pvc







