# 1. Frontend Service (Public Access)
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer # Triggers AWS to create a public URL
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# 2. Backend Service (Internal Access only)
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP # Default internal-only type
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
# 3. MySQL Service (Internal Access only)
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
