apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: lab-shopflow
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1 # Target AWS workspace region
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret-sync
  namespace: lab-shopflow
spec:
  refreshInterval: "1h" # Automatically pulls rotation changes from AWS
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: db-secret # Creates a native Kubernetes Secret named 'db-secret' on the fly
    creationPolicy: Owner
  data:
    - secretKey: db-user
      remoteRef:
        key: enterprise/shopflow/rds
        property: username
    - secretKey: db-password
      remoteRef:
        key: enterprise/shopflow/rds
        property: password
