#Verifying ArgoCD StatusOnce you apply this file (kubectl apply -f argocd-app.yaml -n argocd), 
#you can check the live tracking matrix in your terminal: argocd app get shopflow-enterprise-gitops


# ARGOCD ENTERPRISE GITOPS LIFECYCLE DEPLOYMENT
# ==============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopflow-enterprise-gitops  # Unique identifier for this tracking manager in the ArgoCD UI
  namespace: argocd                 # Mandated: ArgoCD controllers look exclusively inside this namespace for sync rules
spec:
ignoreDifferences:
- group: apps
  kind: Deployment
  jsonPointers:
  - /spec/template/spec/containers/0/image

  # PURPOSE: Segregates cluster administrative access controls.
  # DETAIL: The 'default' project provides full cluster-wide management privileges.
  project: default
  
  # ==============================================================================
  # SOURCE CONTROL TRACKING MECHANISM (GITOPS TRUTH LAYER)
  # ==============================================================================
  source:
    repoURL: 'https://github.com/henoknathan/k8srepo.git' # The Git repository hosting your infrastructure code
    targetRevision: HEAD                                  # Continuously tracks the absolute tip of your default branch
    path: k8s                                             # Instructs ArgoCD to watch your k8s folder exclusively
    
  # ==============================================================================
  # DESTINATION TARGET CONTROL LAYER
  # ==============================================================================
  destination:
    # Changed from 'default.svc' to the standard valid Kubernetes internal local API string
    server: 'https://default.svc'
    
    # Swapped from 'default' to your real enterprise application namespace
    # PURPOSE: Ties the fallback deployment scope directly to your dedicated application environment workspace
    namespace: lab-shopflow
    
  # ==============================================================================
  # SYNCHRONIZATION AND SELF-HEALING ENGINE POLICIES
  # ==============================================================================
  syncPolicy:
    automated:
      # PURPOSE: Prevents configuration drift and removes deprecated architectural components.
      # DETAIL: If a file (like an old service) is deleted from Git, Argo automatically deletes it from EKS.
      prune: true
      
      # PURPOSE: Enforces strict infrastructure state enforcement (Anti-Tampering).
      # DETAIL: If an engineer manually alters a pod or deployment via the CLI ('kubectl edit'), 
      # ArgoCD will instantly overwrite the manual changes and restore the Git configuration.
      selfHeal: true

